# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_savedrecipe'),
    ]

    operations = [
        # Add database index to user field for faster lookups
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
                db_index=True  # Add database index
            ),
        ),
        # Add composite index for frequently queried fields
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(
                fields=['user', 'diabetes_type'],
                name='accounts_userprofile_user_diabetes_idx'
            ),
        ),
        # Add index for updated_at for faster ordering/filtering
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(
                fields=['updated_at'],
                name='accounts_userprofile_updated_at_idx'
            ),
        ),
    ]