# Generated by Django 6.0.3 on 2026-03-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_profile_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='accounts_userprofile_user_diabetes_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='accounts_userprofile_updated_at_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_cholesterol',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
