# Generated by Django 6.0.3 on 2026-04-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
